### ISSUE TITLE
A detailed README

### ISSUE THREAD

**Issue by sayakpaul** [farmaker47/ocr_keras#1]
@farmaker47 since this application is first-of-its-kind, I'd recommend a detailed README to guide the interested developers. Once done, let me know here and I will update [the blog post](https://sayak.dev/optimizing-text-detectors/).

**Comment by farmaker47** [comment]
@sayakpaul I will delete this repo as this is [the one](https://github.com/farmaker47/OCR_with_Keras) I have been using and testing earlier this year. Thanks for the recommendation. I will create a detailed README file there.

**Comment by sayakpaul** [comment]
Alright. Thanks, George.
